server:
  port: 30030
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://45.84.210.174:65432/2023-BFS-1-G3
    username: Fullstack_2023_1_G3
    password: 1qaz2wsx
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace